In [1]:
import torch

In [2]:
class RegressionModel(torch.nn.Module):
    def __init__(self, input_dim, output_dim, hidden_dim):
        super(RegressionModel, self).__init__()
        self.input = torch.nn.Linear(input_dim, hidden_dim)
        self.activation = torch.nn.ReLU()
        self.output = torch.nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        x = self.input(x)
        x = self.activation(x)
        x = self.output(x)
        return x


def train_model(model, X_train, y_train, num_epochs=100, lr=0.01, patience=5):
    best_val_loss = float('inf')
    epochs_without_improvement = 0
    criterion = torch.nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    for epoch in range(num_epochs):
        # Forward pass
        outputs = model(X_train)
        print(outputs)
        loss = criterion(outputs, y_train)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        print(f'Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item():.4f}')

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for inputs in X_train:
                outputs = model(inputs)
                val_loss += criterion(outputs, y_train).item()
        val_loss /= len(X_train)

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1
            if epochs_without_improvement >= patience:
                print("Early stopping triggered!")
                break

    return model


X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
y = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float32)
model1 = RegressionModel(2, 2, 4)
model1 = train_model(model1, X, y, num_epochs=1000, lr=0.01)
model2 = RegressionModel(2, 2, 10)
model2 = train_model(model2, X, y, num_epochs=1000, lr=0.01)
model3 = RegressionModel(2, 2, 15)
model3 = train_model(model3, X, y, num_epochs=1000, lr=0.01)
train_model(model2, X, y, num_epochs=1000, lr=0.15)

tensor([[ 0.1408,  0.4293],
        [-0.0117,  0.5344],
        [ 0.1090,  0.2367],
        [-0.0038,  0.5168]], grad_fn=<AddmmBackward0>)
Epoch [1/1000], Loss: 0.2863
tensor([[0.1468, 0.4296],
        [0.0064, 0.5322],
        [0.1137, 0.2570],
        [0.0154, 0.5113]], grad_fn=<AddmmBackward0>)
Epoch [2/1000], Loss: 0.2776
tensor([[0.1517, 0.4328],
        [0.0240, 0.5354],
        [0.1188, 0.2768],
        [0.0340, 0.5107]], grad_fn=<AddmmBackward0>)
Epoch [3/1000], Loss: 0.2697
tensor([[0.1564, 0.4372],
        [0.0411, 0.5406],
        [0.1243, 0.2962],
        [0.0519, 0.5119]], grad_fn=<AddmmBackward0>)
Epoch [4/1000], Loss: 0.2625
tensor([[0.1611, 0.4417],
        [0.0577, 0.5464],
        [0.1301, 0.3151],
        [0.0690, 0.5133]], grad_fn=<AddmmBackward0>)
Epoch [5/1000], Loss: 0.2558
tensor([[0.1661, 0.4462],
        [0.0737, 0.5523],
        [0.1363, 0.3333],
        [0.0853, 0.5146]], grad_fn=<AddmmBackward0>)
Epoch [6/1000], Loss: 0.2496
tensor([[0.1711, 0.4507],
      

C:\Users\seu21\anaconda3\envs\ai_lab\lib\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([4, 2])) that is different to the input size (torch.Size([2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch [6/1000], Loss: 0.2287
tensor([[0.1414, 0.2164],
        [0.2576, 0.4283],
        [0.0696, 0.5455],
        [0.1916, 0.5903]], grad_fn=<AddmmBackward0>)
Epoch [7/1000], Loss: 0.2092
tensor([[0.1745, 0.2338],
        [0.3163, 0.4449],
        [0.1377, 0.5685],
        [0.2840, 0.5927]], grad_fn=<AddmmBackward0>)
Epoch [8/1000], Loss: 0.1953
tensor([[0.2008, 0.2501],
        [0.3680, 0.4625],
        [0.2004, 0.5911],
        [0.3667, 0.5987]], grad_fn=<AddmmBackward0>)
Epoch [9/1000], Loss: 0.1868
tensor([[0.2202, 0.2637],
        [0.4126, 0.4776],
        [0.2569, 0.6105],
        [0.4418, 0.6014]], grad_fn=<AddmmBackward0>)
Epoch [10/1000], Loss: 0.1815
tensor([[0.2326, 0.2730],
        [0.4477, 0.4873],
        [0.3062, 0.6245],
        [0.5081, 0.5986]], grad_fn=<AddmmBackward0>)
Epoch [11/1000], Loss: 0.1784
tensor([[0.2382, 0.2775],
        [0.4754, 0.4933],
        [0.3474, 0.6324],
        [0.5648, 0.5894]], grad_fn=<AddmmBackward0>)
Epoch [12/1000], Loss: 0.1761
Early st

RegressionModel(
  (input): Linear(in_features=2, out_features=10, bias=True)
  (activation): ReLU()
  (output): Linear(in_features=10, out_features=2, bias=True)
)